### ISSUE TITLE
Why are some import lines deleted?

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#1]
Hi, thanks for writing this plugin, I find it really useful. One quick question, why is that if I write:

``` python
from appscript import k
import xlwings as xw
```

and run `:ImpSort` then I get:

``` python
import xlwings as xw
```

I don't understand why the `appscript` import line gets deleted. Is this a feature? Thanks in advance

**Comment by tweekmonster** [comment]
This is a known problem.  I didn't post this plugin anywhere, so I didn't think it needed my attention right away. 😅 

The issue is because a 1 character module name becomes lost in the module parsing.  I'll take a look at this as soon as I can!

**Comment by petobens** [comment]
Awesome. Thank  you!

**Comment by tweekmonster** [comment]
@petobens This should be fixed now!

**Comment by petobens** [comment]
Hi @tweekmonster , thanks for the previous fix. I found another case where import lines are deleted. If I write

``` python
from pyhive import presto
from pyhive.exc import DatabaseError
```

and then run `:ImpSort` I get:

``` python
from pyhive.exc import DatabaseError
```

Can this be fixed? Thanks

**Comment by tweekmonster** [comment]
@petobens I fixed this today in the latest commit.  Make sure you're up to date.  The problem was with the sorting function.

**Comment by petobens** [comment]
@tweekmonster I believe I'm using the latest version however I still see the behaviour. Can you reproduce it? Again thanks for the help

**Comment by tweekmonster** [comment]
@petobens I think I found the issue.  Are the imports the only thing that's in the file?  Try adding any non-import after them.  If that's the issue you're having, I'll look into fixing it.

**Comment by petobens** [comment]
@tweekmonster , adding non-import lines indeed fixes the issue.

**Comment by tweekmonster** [comment]
Thanks!  I narrowed down the issue.  A fix will be inbound shortly.

**Comment by tweekmonster** [comment]
@petobens Should be fixed now.  Thanks for finding these issues!

**Comment by petobens** [comment]
Thank you for fixing them so quickly! :)
